name: Update Homebrew Formula

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., 1.0.0)'
        required: true

jobs:
  update-brew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Download release artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Clone homebrew-gitnapped tap
        run: |
          git clone https://x-access-token:${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/solexma/homebrew-gitnapped.git tap-repo
          cd tap-repo

          # Get version from the release tag or manual input
          VERSION=${{ github.event.workflow_run.head_branch != '' && format('{0}', github.event.workflow_run.head_branch) || inputs.version }}
          VERSION=$(echo $VERSION | sed 's/v//')
          echo "Updating to version: $VERSION"

          # Update version
          sed -i "s|version \".*\"|version \"$VERSION\"|" Formula/gitnapped.rb

          # Read SHA256s from files
          SHA256_X86_64_DARWIN=$(cat ../artifacts/gitnapped-x86_64-apple-darwin/gitnapped-x86_64-apple-darwin.tar.gz.sha256 | awk '{print $1}')
          SHA256_AARCH64_DARWIN=$(cat ../artifacts/gitnapped-aarch64-apple-darwin/gitnapped-aarch64-apple-darwin.tar.gz.sha256 | awk '{print $1}')
          SHA256_X86_64_LINUX=$(cat ../artifacts/gitnapped-x86_64-unknown-linux-gnu/gitnapped-x86_64-unknown-linux-gnu.tar.gz.sha256 | awk '{print $1}')

          # Update URLs and SHA256s for each platform
          # macOS Intel
          sed -i "/if OS.mac? && Hardware::CPU.intel?/,/url/s|url \".*\"|url \"https://github.com/solexma/gitnapped/releases/download/v$VERSION/gitnapped-x86_64-apple-darwin.tar.gz\"|" Formula/gitnapped.rb
          sed -i "/if OS.mac? && Hardware::CPU.intel?/,/sha256/s|sha256 \".*\"|sha256 \"$SHA256_X86_64_DARWIN\"|" Formula/gitnapped.rb

          # macOS ARM
          sed -i "/elsif OS.mac? && Hardware::CPU.arm?/,/url/s|url \".*\"|url \"https://github.com/solexma/gitnapped/releases/download/v$VERSION/gitnapped-aarch64-apple-darwin.tar.gz\"|" Formula/gitnapped.rb
          sed -i "/elsif OS.mac? && Hardware::CPU.arm?/,/sha256/s|sha256 \".*\"|sha256 \"$SHA256_AARCH64_DARWIN\"|" Formula/gitnapped.rb

          # Linux
          sed -i "/elsif OS.linux? && Hardware::CPU.intel?/,/url/s|url \".*\"|url \"https://github.com/solexma/gitnapped/releases/download/v$VERSION/gitnapped-x86_64-unknown-linux-gnu.tar.gz\"|" Formula/gitnapped.rb
          sed -i "/elsif OS.linux? && Hardware::CPU.intel?/,/sha256/s|sha256 \".*\"|sha256 \"$SHA256_X86_64_LINUX\"|" Formula/gitnapped.rb

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Formula/gitnapped.rb

          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Update gitnapped.rb to version $VERSION"
            git push https://x-access-token:${{ secrets.HOMEBREW_TAP_TOKEN }}@github.com/solexma/homebrew-gitnapped.git HEAD:main
          fi 